#pragma once

#ifndef WINTILES_WTVERSION_IN_H
#define WINTILES_WTVERSION_IN_H

#define APPNAME "WinTiles"
#define VERSION @PROJECT_VERSION_MAJOR@,@PROJECT_VERSION_MINOR@,@PROJECT_VERSION_PATCH@,0
#define VERSION_STR "V@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@.@PROJECT_VERSION_PATCH@"

#endif //WINTILES_WTVERSION_IN_H
